# Generated by Django 5.1.6 on 2025-03-04 09:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestsellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./images')),
                ('title', models.CharField(max_length=1000)),
                ('title_uz', models.CharField(max_length=1000, null=True)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('info', ckeditor.fields.RichTextField()),
                ('info_uz', ckeditor.fields.RichTextField(null=True)),
                ('info_ru', ckeditor.fields.RichTextField(null=True)),
                ('descript_text', ckeditor.fields.RichTextField()),
                ('descript_text_uz', ckeditor.fields.RichTextField(null=True)),
                ('descript_text_ru', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_uz', models.CharField(max_length=1000, null=True)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('img', models.ImageField(upload_to='./images')),
                ('info', ckeditor.fields.RichTextField()),
                ('info_uz', ckeditor.fields.RichTextField(null=True)),
                ('info_ru', ckeditor.fields.RichTextField(null=True)),
                ('descript_text', ckeditor.fields.RichTextField()),
                ('descript_text_uz', ckeditor.fields.RichTextField(null=True)),
                ('descript_text_ru', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./images')),
                ('title', models.CharField(max_length=1000)),
                ('title_uz', models.CharField(max_length=1000, null=True)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('info', ckeditor.fields.RichTextField()),
                ('info_uz', ckeditor.fields.RichTextField(null=True)),
                ('info_ru', ckeditor.fields.RichTextField(null=True)),
                ('descript_text', ckeditor.fields.RichTextField()),
                ('descript_text_uz', ckeditor.fields.RichTextField(null=True)),
                ('descript_text_ru', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullimg', models.ImageField(upload_to='./images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopRated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./images')),
                ('title', models.CharField(max_length=1000)),
                ('title_uz', models.CharField(max_length=1000, null=True)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('info', ckeditor.fields.RichTextField()),
                ('info_uz', ckeditor.fields.RichTextField(null=True)),
                ('info_ru', ckeditor.fields.RichTextField(null=True)),
                ('descript_text', ckeditor.fields.RichTextField()),
                ('descript_text_uz', ckeditor.fields.RichTextField(null=True)),
                ('descript_text_ru', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_uz', models.CharField(max_length=1000, null=True)),
                ('title_ru', models.CharField(max_length=1000, null=True)),
                ('img', models.ImageField(upload_to='./images')),
                ('info', ckeditor.fields.RichTextField()),
                ('info_uz', ckeditor.fields.RichTextField(null=True)),
                ('info_ru', ckeditor.fields.RichTextField(null=True)),
                ('descript_text', ckeditor.fields.RichTextField()),
                ('descript_text_uz', ckeditor.fields.RichTextField(null=True)),
                ('descript_text_ru', ckeditor.fields.RichTextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('productclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('dec_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='OnlyOneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./images')),
                ('productclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productclass')),
            ],
        ),
    ]
