# Generated by Django 5.1.6 on 2025-03-17 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_status_product_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bestsellers',
        ),
        migrations.DeleteModel(
            name='Special',
        ),
        migrations.DeleteModel(
            name='TopRated',
        ),
    ]
