# Generated by Django 5.1.6 on 2025-03-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_bestsellers_delete_special_delete_toprated'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productclass',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
